name: Release
on:
  push:
    tags: ['v*']

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build csend
        run: cmake -B build && cmake --build build
      - name: Package
        run: tar czf csend-posix-linux-x64.tar.gz -C build csend-posix
      - name: Create Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v2
        with:
          files: csend-posix-linux-x64.tar.gz
